# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProductFinder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProductFinder
  pod 'Alamofire', '5.6.3'
  pod 'SwiftFormat/CLI'
  pod 'SwiftLint'
  pod 'lottie-ios'

  target 'ProductFinderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProductFinderUITests' do
    # Pods for testing
  end

end
